### ISSUE TITLE
openITCOCKPIT 4.2 - Todo List Release

### ISSUE THREAD

**Issue by nook24** [it-novum/openITCOCKPIT#1158]
Repos to merge: (development into master)

- [x] https://github.com/it-novum/openITCOCKPIT
- [x] https://github.com/it-novum/openITCOCKPIT-modules
- [x] https://github.com/it-novum/openitcockpit-receiver
- [x] https://github.com/it-novum/graphing-docker

Issues to close

- [x] #1144
- [x] #977
- [x] #1082
- [x] #1168
